## 2.6 - Python: Numpy

### Soru 1:

In [3]:
# 1'den 200'ye kadar olan çift sayılardan oluşan 10 X 10'luk bir dizi oluşturun. arange() fonksiyonu yardımcı olabilir.

import numpy as np

cift_dizi = np.arange(2,201,2).reshape(10,10)
print(cift_dizi)
print("\nMatrisin boyutu: ", np.shape(cift_dizi))

[[  2   4   6   8  10  12  14  16  18  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 42  44  46  48  50  52  54  56  58  60]
 [ 62  64  66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  94  96  98 100]
 [102 104 106 108 110 112 114 116 118 120]
 [122 124 126 128 130 132 134 136 138 140]
 [142 144 146 148 150 152 154 156 158 160]
 [162 164 166 168 170 172 174 176 178 180]
 [182 184 186 188 190 192 194 196 198 200]]

Matrisin boyutu:  (10, 10)


### Soru 2:

In [11]:
# Parametre olarak girilen satır ve kolon sayısına göre kenarları 1'lerden,
# içi 0'lardan oluşan dizi döndüren bir fonksiyon yazınız.

try:
    row = int(input("Lütfen matrisin satır sayısını giriniz: "))
    column = int(input("Sütun sayısını giriniz: "))
    
    def kenar(a,b):
        box = np.ones([a,b])
        box[1:a-1,1:b-1]=0    # görüşmeden sonra düzeltildi.
        print("\n", box)        
    
    kenar(row,column)
    
except:
    print("\nLütfen 0'dan büyük bir sayı giriniz.")

Lütfen matrisin satır sayısını giriniz: 7
Sütun sayısını giriniz: 9

 [[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
